[2024-04-22T16:57:38.483+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T16:57:38.488+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T16:57:38.488+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:57:38.499+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-29 00:00:00+00:00
[2024-04-22T16:57:38.502+0000] {standard_task_runner.py:60} INFO - Started process 167425 to run task
[2024-04-22T16:57:38.505+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmprz_5gfqk']
[2024-04-22T16:57:38.505+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask read_equipements
[2024-04-22T16:57:38.537+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:57:38.588+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-22T16:57:38.589+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:57:38.594+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:57:38.594+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:57:38.598+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240329T000000, start_date=20240422T165738, end_date=20240422T165738
[2024-04-22T16:57:38.607+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task read_equipements ('NoneType' object has no attribute 'date'; 167425)
[2024-04-22T16:57:38.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:57:38.651+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:43:51.137+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T17:43:51.143+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T17:43:51.143+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:43:51.156+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-29 00:00:00+00:00
[2024-04-22T17:43:51.159+0000] {standard_task_runner.py:60} INFO - Started process 207666 to run task
[2024-04-22T17:43:51.161+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmplljds2_s']
[2024-04-22T17:43:51.162+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask read_equipements
[2024-04-22T17:43:51.215+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:43:51.289+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-22T17:43:51.290+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:43:51.290+0000] {logging_mixin.py:188} INFO - intervals is [<Proxy at 0x7f9c74a61440 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f9c74a905e0>, 'prev_execution_date_success', None)>, <Proxy at 0x7f9c74a4fb40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f9c74a905e0>, 'execution_date', DateTime(2024, 3, 29, 0, 0, 0, tzinfo=Timezone('UTC')))>]
[2024-04-22T17:43:53.210+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:43:53.211+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 56, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 56, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:43:53.215+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240329T000000, start_date=20240422T174351, end_date=20240422T174353
[2024-04-22T17:43:53.227+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task read_equipements ('NoneType' object has no attribute 'date'; 207666)
[2024-04-22T17:43:53.259+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:43:53.279+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:19:07.568+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T18:19:07.575+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-22T18:19:07.576+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:19:07.589+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-29 00:00:00+00:00
[2024-04-22T18:19:07.592+0000] {standard_task_runner.py:60} INFO - Started process 238013 to run task
[2024-04-22T18:19:07.595+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpbe_sxzai']
[2024-04-22T18:19:07.596+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask read_equipements
[2024-04-22T18:19:07.625+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-29T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:19:07.663+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:19:07.686+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-22T18:19:07.687+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:19:07.687+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-29 00:00:00+00:00', '2024-03-29 00:00:00+00:00']
[2024-04-22T18:19:09.802+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:19:09.824+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240329T000000, start_date=20240422T181907, end_date=20240422T181909
[2024-04-22T18:19:09.853+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:19:09.883+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-29T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:19:09.890+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
