[2024-04-23T12:43:20.868+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=12 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'read_equipements'}
[2024-04-23T12:43:20.869+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-04-23T12:44:45.576+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=12 [queued]>
[2024-04-23T12:44:45.581+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=12 [queued]>
[2024-04-23T12:44:45.581+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T12:44:45.592+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): push_in_redis> on 2024-04-23 11:54:48.966898+00:00
[2024-04-23T12:44:45.596+0000] {standard_task_runner.py:60} INFO - Started process 154415 to run task
[2024-04-23T12:44:45.598+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'push_in_redis', 'manual__2024-04-23T11:54:48.966898+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp4ws235mn', '--map-index', '12']
[2024-04-23T12:44:45.598+0000] {standard_task_runner.py:88} INFO - Job 320: Subtask push_in_redis
[2024-04-23T12:44:45.621+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=12 [running]> on host datalab-yasmine
[2024-04-23T12:44:45.755+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='push_in_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T11:54:48.966898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T11:54:48.966898+00:00'
[2024-04-23T12:44:45.756+0000] {pipeline_eq.py:90} INFO - start to push data in redis
[2024-04-23T12:44:47.315+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 94, in push_in_redis
    key = uuid.UUID('hex')
  File "/home/yasmine/.pyenv/versions/3.8.16/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
[2024-04-23T12:44:47.318+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=push_in_redis, map_index=12, execution_date=20240423T115448, start_date=20240423T124445, end_date=20240423T124447
[2024-04-23T12:44:47.326+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 320 for task push_in_redis (badly formed hexadecimal UUID string; 154415)
[2024-04-23T12:44:47.342+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T12:44:47.349+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
