[2024-04-23T11:10:10.315+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
