[2024-04-22T16:57:06.907+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T16:57:06.912+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T16:57:06.913+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:57:06.924+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-19 00:00:00+00:00
[2024-04-22T16:57:06.926+0000] {standard_task_runner.py:60} INFO - Started process 166605 to run task
[2024-04-22T16:57:06.929+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp0_i9y7h8']
[2024-04-22T16:57:06.929+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask read_equipements
[2024-04-22T16:57:06.960+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:57:07.017+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-04-22T16:57:07.018+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:57:07.023+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:57:07.024+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:57:07.028+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240319T000000, start_date=20240422T165706, end_date=20240422T165707
[2024-04-22T16:57:07.038+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task read_equipements ('NoneType' object has no attribute 'date'; 166605)
[2024-04-22T16:57:07.060+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:57:07.075+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:14:06.105+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T17:14:06.112+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T17:14:06.113+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:14:06.125+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-19 00:00:00+00:00
[2024-04-22T17:14:06.128+0000] {standard_task_runner.py:60} INFO - Started process 184173 to run task
[2024-04-22T17:14:06.132+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpdqv5yz4m']
[2024-04-22T17:14:06.133+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask read_equipements
[2024-04-22T17:14:06.160+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:14:06.208+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-04-22T17:14:06.208+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:14:06.209+0000] {logging_mixin.py:188} INFO - [<Proxy at 0x7f5f363bf580 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5f363ed5e0>, 'prev_execution_date_success', None)>, <Proxy at 0x7f5f364136c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7f5f363ed5e0>, 'execution_date', DateTime(2024, 3, 19, 0, 0, 0, tzinfo=Timezone('UTC')))>]
[2024-04-22T17:14:08.227+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:14:08.227+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:14:08.231+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240319T000000, start_date=20240422T171406, end_date=20240422T171408
[2024-04-22T17:14:08.241+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task read_equipements ('NoneType' object has no attribute 'date'; 184173)
[2024-04-22T17:14:08.269+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:14:08.286+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:18:17.833+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T18:18:17.841+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-04-22T18:18:17.841+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:18:17.854+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-19 00:00:00+00:00
[2024-04-22T18:18:17.857+0000] {standard_task_runner.py:60} INFO - Started process 236821 to run task
[2024-04-22T18:18:17.859+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp80uzuna4']
[2024-04-22T18:18:17.860+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask read_equipements
[2024-04-22T18:18:17.885+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-19T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:18:17.919+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:18:17.939+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-04-22T18:18:17.940+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:18:17.940+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-19 00:00:00+00:00', '2024-03-19 00:00:00+00:00']
[2024-04-22T18:18:19.932+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:18:19.948+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240319T000000, start_date=20240422T181817, end_date=20240422T181819
[2024-04-22T18:18:19.998+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:18:20.023+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-19T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:18:20.028+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
